// Copyright 2026 example. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

// Package learn implements the recall/teach loop for entity lookups and ticker
// patterns. The package is generator-owned and re-emitted on every regen.

package learn

// Recall returns a cached completion for the given query, or empty when no
// pattern matches.
func Recall(query string) string { return "" }

// Teach writes the (query, answer) pair back to the local store for the next
// caller to pick up via Recall.
func Teach(query, answer string) error { return nil }
