// Copyright 2026 example. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package learn

// Patterns is a stub for the FTS-backed pattern store. Real implementation
// lives downstream of the learn-loop generator; the test fixture only needs
// the file to exist for classification.

type Patterns struct{}

func (Patterns) Match(string) string { return "" }
