// Copyright 2026. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package main

import (
	"fmt"
	"os"

	mcptools "ble-temperature-sensor-pp-cli/internal/mcp"
	"github.com/mark3labs/mcp-go/server"
)

// version is the printed MCP server's version, overridable at build time via ldflags.
var version = "1.0.0"

func main() {
	s := server.NewMCPServer(
		"BLE Temperature Sensor",
		version,
		server.WithToolCapabilities(false),
	)
	mcptools.RegisterTools(s)
	if err := server.ServeStdio(s); err != nil {
		fmt.Fprintf(os.Stderr, "MCP server error: %v\n", err)
		os.Exit(1)
	}
}
