// Copyright 2026 printing-press-golden. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newProjectsAvatarCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "avatar",
		Short: "Manage avatar",
		RunE:  parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newProjectsAvatarUploadProjectCmd(flags))
	return cmd
}
