// Copyright 2026 example. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import "github.com/spf13/cobra"

// teach.go is fresh-only. The published tree predates the learn-loop emission,
// so the file appears as NEW-TEMPLATE-EMISSION on regen-merge.

func newTeachCmd(flags *rootFlags) *cobra.Command {
	return &cobra.Command{Use: "teach"}
}
