// Copyright 2026 example. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

type rootFlags struct{}

func Execute() error {
	rootCmd := &cobra.Command{Use: "learn-loop-emission-pp-cli"}
	flags := &rootFlags{}

	rootCmd.AddCommand(newDoctorCmd(flags))
	rootCmd.AddCommand(newVersionCliCmd())

	return rootCmd.Execute()
}
